### ISSUE TITLE
Wrongly added Automatic Linebreak after confirming text

### ISSUE THREAD

**Issue by HabelFLX** [devforth/painterro#183] opened 2023-07-31 07:20 UTC
**Describe the bug**
When I add a long text to my image in a way that the text would exceed the canvas' boundaries, automatic linebreaks are added in the preview. But as soon as I confirm the text by clicking the checkmark button, the added linebreaks change so that parts of the text are not visible anymore.

**Painterro version**
E.g. v1.0.2

**To Reproduce**
1. Open any image
2. Add a new Text and start typing a long sentence
3. when you reach the canvas' boundaries, linebreaks will be added automatically (as expected)
4. confirm the text
5. now the linebreak changes and some text is outside the canvas

**Expected behavior**
The added linebreaks in the preview are correctly displayed. After confirming the text the linebreak should match the preview.

**Screenshots**
![image](https://github.com/devforth/painterro/assets/124193638/190f76ae-6857-4d82-aa60-55408224b02e)
![image](https://github.com/devforth/painterro/assets/124193638/ea5d9d36-7247-453f-a410-872e450b033a)

**Browser**
 - Google Chrome V 114 on Windows

**Comment by ivictbor** [comment] 2024-03-05 20:30
Yes, known issue, started happening after upgrading html to canvas some time ago, once we will have any free time or budget in patreon we will fix this one as prio

**Comment by IhorStorozhok** [comment] 2024-04-10 09:15
Duplicate of #154

**Closed by IhorStorozhok** 2024-04-10 09:15 UTC
Labels: bug, priority
