### ISSUE TITLE
inserter.js doesn't close modal with paste choices on ESC

### ISSUE THREAD

**Issue by MarcDevol** [devforth/painterro#185] opened 2023-08-10 10:43 UTC
**Describe the bug**
When inserter show modal with options how to past image from cliboard, esc button doesn't close window.

**Painterro version**
1.2.82

**To Reproduce**
1. add png image to your clipboard
2. paste image (CTRL + v)
3. push ESC - nothing happend

**Expected behavior**
ESC button close modal window

**Browser**
doesn't metter

**Solution**
1) in main.js in keydown add 'if (this.inserter.handleKeyDown(e)) { return }'
2) in inserter.js in 'handleKeyDown' replace 'event' with 'this' in condition

**Comment by IhorStorozhok** [comment] 2023-12-19 13:57
@MarcDevol 
HI , we can't reproduce this issue . If you still struggling with it ,please create small demo , with simple steps to reproduce it.

**Comment by ivictbor** [comment] 2024-01-30 11:11
@MarcDevol closing because we have no code to reproduce the bug and can't reproduce it by ourselves

**Closed by ivictbor** 2024-01-30 11:11 UTC
