### ISSUE TITLE
Mobile Devices  ||  Touch Event Error  ||  painterro.commonjs2.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'clientX') 

### ISSUE THREAD

**Issue by ravishankardubey** [devforth/painterro#160] opened 2021-11-22 19:32 UTC
**Describe the bug**
When using Painterro on any of the mobile devices, it keeps on throwing the below error 

> painterro.commonjs2.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'clientX')

This Error Leads to refresh of the page in iPad and other mobile devices

**Painterro version**
 v1.2.65

**To Reproduce**
1. Open the live demo link provided in the readme.md file from any mobile device
2. Try interacting with. your two fingers on the screen
3. Check out the developer console
4. iPad leads to refreshing the page after some time of use

**Expected behavior**
Touchpoints should not block anything instead, it should work properly

**Screenshots**

![Screenshot 2021-11-23 at 1 02 00 AM](https://user-images.githubusercontent.com/29010724/142923595-b94d8ce5-c0cb-4a50-a16b-64dd13e5df7a.png)

**Comment by ivictbor** [comment] 2021-11-22 20:18
Hi, thanks a lot for the issue, we will have to take a look on this one and return with a fix

**Comment by Achraffawzi** [comment] 2022-03-04 15:10
did you fix the issue? because I'm facing it as well today.

**Comment by affan00** [comment] 2023-02-01 16:15
any update on this?

**Comment by ivictbor** [comment] 2023-02-01 20:46
Not yet. Unfortunetely it is war in our country from Feb 24 so we can't allow ourselfs to spent time on unpaid work. Only commercial development. Feel free to submit PR

**Comment by IhorStorozhok** [comment] 2024-04-11 09:00
Duplicate of issue #151

**Closed by IhorStorozhok** 2024-04-11 09:00 UTC
Labels: bug, priority
